In [1]:
import numpy as np
# Sample array of IPL team names with duplicates
ipl_teams = np.array([
    "Mumbai Indians", "Chennai Super Kings", "Royal Challengers Bangalore",
    "Kolkata Knight Riders", "Delhi Capitals", "Sunrisers Hyderabad",
    "Rajasthan Royals", "Punjab Kings", "Mumbai Indians", "Delhi Capitals"
])
unique_teams = np.unique(ipl_teams)
print("Unique IPL teams:")
for team in unique_teams:
    print(team)


Unique IPL teams:
Chennai Super Kings
Delhi Capitals
Kolkata Knight Riders
Mumbai Indians
Punjab Kings
Rajasthan Royals
Royal Challengers Bangalore
Sunrisers Hyderabad


In [2]:
import numpy as np

ratings = np.array([4.5, np.nan, 3.8, 5.0, np.nan, 4.2, np.nan, 4.9])
missing_mask = np.isnan(ratings)
missing_count = np.sum(missing_mask)
print("Ratings array:", ratings)
print("Boolean mask :", missing_mask)
print("Missing ratings count:", missing_count)

Ratings array: [4.5 nan 3.8 5.  nan 4.2 nan 4.9]
Boolean mask : [False  True False False  True False  True False]
Missing ratings count: 3


In [3]:
import numpy as np

product_prices = np.array([49, 150, 899, 1299, 85, 500, 2499, 99])
clipped_prices = np.clip(product_prices, 100, 1000)
print("Original Prices:")
print(product_prices)
print("\nClipped Prices (between 100 and 1000):")
print(clipped_prices)

Original Prices:
[  49  150  899 1299   85  500 2499   99]

Clipped Prices (between 100 and 1000):
[ 100  150  899 1000  100  500 1000  100]


In [4]:
import numpy as np

views = np.array([1250.0, np.nan, 8500.0, np.inf, 3200.0, -np.inf, np.nan, 95000.0])
max_finite_val = np.max(views[np.isfinite(views)])
views[np.isnan(views)] = 0
views[np.isinf(views)] = max_finite_val

print(f"Max finite value: {max_finite_val}")
print("Cleaned views array:")
print(views)

Max finite value: 95000.0
Cleaned views array:
[ 1250.     0.  8500. 95000.  3200. 95000.     0. 95000.]


In [5]:
import numpy as np

arr = np.array([13, 24, 35, 42, 50, 61, 78, 91, 102])
even_indices = np.where(arr % 2 == 0)
even_values = arr[even_indices]

print("Original Array :", arr)
print("Even Indices   :", even_indices)
print("Even Values    :", even_values)

Original Array : [ 13  24  35  42  50  61  78  91 102]
Even Indices   : (array([1, 3, 4, 6, 8]),)
Even Values    : [ 24  42  50  78 102]
