In [2]:
import numpy as np

# Number of likes on 7 Instagram posts
post_likes = np.array([1250, 430, 2890, 815, 3400, 190, 5200])

print("Instagram Post Likes Array:", post_likes)
print("ndim     (Number of dimensions):", post_likes.ndim)
print("shape    (Dimensions tuple):    ", post_likes.shape)
print("size     (Total elements):      ", post_likes.size)
print("dtype    (Data type):           ", post_likes.dtype)
print("itemsize (Bytes per element):   ", post_likes.itemsize)
print("nbytes   (Total bytes used):    ", post_likes.nbytes)

Instagram Post Likes Array: [1250  430 2890  815 3400  190 5200]
ndim     (Number of dimensions): 1
shape    (Dimensions tuple):     (7,)
size     (Total elements):       7
dtype    (Data type):            int64
itemsize (Bytes per element):    8
nbytes   (Total bytes used):     56


In [3]:
import numpy as np

# 1. Create a 2D array (5 days x 2 sessions: Morning, Evening)
step_counts = np.array([
    [3200, 4500],  
    [4100, 5200],  
    [2800, 3900],  
    [5000, 6100],  
    [3600, 4800]   
])

print("Original 2D Array:")
print(step_counts)
print("Original shape:", step_counts.shape)

steps_1d = step_counts.reshape(-1)

print("\nReshaped to 1D:")
print(steps_1d)
print("1D shape:", steps_1d.shape)

steps_2d = steps_1d.reshape(5, 2)

print("\nReshaped back to 2D (5x2):")
print(steps_2d)
print("Restored shape:", steps_2d.shape)

Original 2D Array:
[[3200 4500]
 [4100 5200]
 [2800 3900]
 [5000 6100]
 [3600 4800]]
Original shape: (5, 2)

Reshaped to 1D:
[3200 4500 4100 5200 2800 3900 5000 6100 3600 4800]
1D shape: (10,)

Reshaped back to 2D (5x2):
[[3200 4500]
 [4100 5200]
 [2800 3900]
 [5000 6100]
 [3600 4800]]
Restored shape: (5, 2)


In [4]:
import numpy as np

# 1. 2D array of 12 food item prices (e.g., 3 orders x 4 items)
zomato_prices = np.array([
    [120, 250, 80, 45],
    [320, 150, 99, 210],
    [180, 310, 60, 140]
])

print("Original 2D Prices Array (3x4):")
print(zomato_prices)
print("Shape:", zomato_prices.shape)

raveled_prices = zomato_prices.ravel()

print("\nFlattened with ravel():")
print(raveled_prices)
print("Shape:", raveled_prices.shape)


flattened_prices = zomato_prices.flatten()

print("\nFlattened with flatten():")
print(flattened_prices)
print("Shape:", flattened_prices.shape)

# Demonstrate the memory difference:
raveled_prices[0] = 999     
flattened_prices[1] = 888   

print("\n--- After Mutating ravel() and flatten() ---")
print(f"Original item [0, 0] after ravel change:   {zomato_prices[0, 0]} (Changed!)")
print(f"Original item [0, 1] after flatten change: {zomato_prices[0, 1]} (Unchanged)")

# Reset item back
zomato_prices[0, 0] = 120

resized_2x6 = np.resize(zomato_prices, (2, 6))
print("\nResized to (2, 6) using np.resize():")
print(resized_2x6)
print("Shape:", resized_2x6.shape)

# Expanding to (4, 4) - 16 elements (np.resize cycles the elements)
resized_expanded = np.resize(zomato_prices, (4, 4))
print("\nResized to larger shape (4, 4) [repeats data]:")
print(resized_expanded)
print("Shape:", resized_expanded.shape)

Original 2D Prices Array (3x4):
[[120 250  80  45]
 [320 150  99 210]
 [180 310  60 140]]
Shape: (3, 4)

Flattened with ravel():
[120 250  80  45 320 150  99 210 180 310  60 140]
Shape: (12,)

Flattened with flatten():
[120 250  80  45 320 150  99 210 180 310  60 140]
Shape: (12,)

--- After Mutating ravel() and flatten() ---
Original item [0, 0] after ravel change:   999 (Changed!)
Original item [0, 1] after flatten change: 250 (Unchanged)

Resized to (2, 6) using np.resize():
[[120 250  80  45 320 150]
 [ 99 210 180 310  60 140]]
Shape: (2, 6)

Resized to larger shape (4, 4) [repeats data]:
[[120 250  80  45]
 [320 150  99 210]
 [180 310  60 140]
 [120 250  80  45]]
Shape: (4, 4)


In [5]:
import numpy as np

# Rows: Playlists (e.g., Workout, Chill, Party)
# Columns: Song counts (Pop, Rock, Indie)
spotify_grid = np.array([
    [15, 8, 4],   
    [5, 20, 12],  
    [10, 3, 18]   
])

print("Original Grid (Rows: Playlists, Cols: Genres):")
print(spotify_grid)

# 1. Transpose using the .T attribute
transposed_t = spotify_grid.T

# 2. Transpose using the np.transpose() function
transposed_func = np.transpose(spotify_grid)

print("\nTransposed via .T (Rows: Genres, Cols: Playlists):")
print(transposed_t)

print("\nTransposed via np.transpose():")
print(transposed_func)

# Verify both approaches yield identical results
print("\nAre both results identical?:", np.array_equal(transposed_t, transposed_func))

Original Grid (Rows: Playlists, Cols: Genres):
[[15  8  4]
 [ 5 20 12]
 [10  3 18]]

Transposed via .T (Rows: Genres, Cols: Playlists):
[[15  5 10]
 [ 8 20  3]
 [ 4 12 18]]

Transposed via np.transpose():
[[15  5 10]
 [ 8 20  3]
 [ 4 12 18]]

Are both results identical?: True


In [6]:
import numpy as np

# 1. 1D array of 15 Flipkart product ratings (scale 1 to 5)
flipkart_ratings = np.array([4.2, 3.8, 4.5, 2.9, 5.0, 
                             4.1, 3.6, 4.8, 1.5, 4.0, 
                             3.9, 4.7, 4.3, 2.5, 4.9])

print("Original 1D Ratings:")
print(flipkart_ratings)
print("Shape:", flipkart_ratings.shape)

# 2. Reshape into a 3x5 2D array (e.g., 3 product categories, 5 products each)
ratings_3x5 = flipkart_ratings.reshape(3, 5)

print("\nReshaped to 3x5 Array:")
print(ratings_3x5)
print("Shape:", ratings_3x5.shape)

# 3. Return back to 1D using flatten()
restored_1d = ratings_3x5.flatten()

print("\nRestored to 1D via flatten():")
print(restored_1d)
print("Shape:", restored_1d.shape)


Original 1D Ratings:
[4.2 3.8 4.5 2.9 5.  4.1 3.6 4.8 1.5 4.  3.9 4.7 4.3 2.5 4.9]
Shape: (15,)

Reshaped to 3x5 Array:
[[4.2 3.8 4.5 2.9 5. ]
 [4.1 3.6 4.8 1.5 4. ]
 [3.9 4.7 4.3 2.5 4.9]]
Shape: (3, 5)

Restored to 1D via flatten():
[4.2 3.8 4.5 2.9 5.  4.1 3.6 4.8 1.5 4.  3.9 4.7 4.3 2.5 4.9]
Shape: (15,)
