In [3]:
import numpy as np

prices = np.array([199, 299, 399, 499, 599])
print("First price:", prices[0])
print("Last price:", prices[-2])

First price: 199
Last price: 499


In [2]:
import numpy as np

scores = np.array([
    [45, 12, 78, 34, 90],  
    [60, 85,  5, 40, 55],  
    [10, 25, 30, 45, 50]   
])

extracted_scores = scores[:, 1:4]

print(extracted_scores)

[[12 78 34]
 [85  5 40]
 [25 30 45]]


In [6]:
import numpy as np
ratings = np.array([4.5, 3.8, 4.2, 2.9, 5.0, 3.5])
last_three = ratings[-3:]
print(last_three)

[2.9 5.  3.5]


In [7]:
import numpy as np
numbers = np.arange(1, 21)
result = numbers[1::3]
print("Numbers array:", numbers)
print("Every 3rd number from 2nd element:", result)

Numbers array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Every 3rd number from 2nd element: [ 2  5  8 11 14 17 20]


In [ ]:
import numpy as np

prices = np.array([249, 799, 1299, 499, 550, 199, 899])
expensive_prices = prices[prices > 500]
print("Original prices:", prices)
print("Prices greater than 500:", expensive_prices)

Original prices: [ 249  799 1299  499  550  199  899]
Prices greater than 500: [ 799 1299  550  899]


In [9]:
import numpy as np

scores = np.array([210, 180, 195, 220, 205, 175])
indices = np.where(scores > 200)
print("Indices of scores above 200:", indices[0])

Indices of scores above 200: [0 3 4]
