In [1]:
import numpy as np

# Create the array with 5 order ratings (integers from 1 to 5)
my_scores = np.array([5, 4, 4, 3, 5])

# Print the array
print("my_scores:", my_scores)
print("Data type:", my_scores.dtype)
print("Shape:    ", my_scores.shape)

my_scores: [5 4 4 3 5]
Data type: int64
Shape:     (5,)


In [2]:
import numpy as np

# stop is set to 32 because the end value in np.arange() is exclusive
even_numbers = np.arange(10, 32, 2)

print("Even numbers from 10 to 30 (inclusive):")
print(even_numbers)

Even numbers from 10 to 30 (inclusive):
[10 12 14 16 18 20 22 24 26 28 30]


In [3]:
import numpy as np

# Generate 8 evenly spaced volume steps from 0.0 (mute) to 1.0 (max)
volume_slider = np.linspace(0, 1, 8)

print("Volume slider steps:")
print(volume_slider)

Volume slider steps:
[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.        ]


In [4]:
import numpy as np

# 1. Initialize cart counters for 10 items to zero
cart = np.zeros(10, dtype=int)

# 2. Add the 3rd and 7th items to cart (using 0-based indexing: index 2 and index 6)
cart[2] = 1
cart[6] = 1

# 3. Print the updated cart state
print("Updated Cart Array:")
print(cart)

Updated Cart Array:
[0 0 1 0 0 0 1 0 0 0]


In [5]:
import numpy as np

# 1. Set seed for reproducible results
np.random.seed(42)

# 2. Generate 6 random 4-digit OTP codes between 1000 and 9999 (inclusive)
# Note: high=10000 because the upper bound in np.random.randint() is exclusive
otp_codes = np.random.randint(low=1000, high=10000, size=6)

# 3. Print the generated array
print("Generated OTPs:")
print(otp_codes)

Generated OTPs:
[8270 1860 6390 6191 6734 7265]
