In [1]:
import numpy as np

zomato_ratings = np.array([4.2, 3.8, 4.5, 4.0, 4.7])
swiggy_ratings = np.array([4.1, 3.9, 4.6, 3.7, 4.8])
combined_ratings = np.concatenate((zomato_ratings, swiggy_ratings))
print("Combined Ratings:")
print(combined_ratings)

Combined Ratings:
[4.2 3.8 4.5 4.  4.7 4.1 3.9 4.6 3.7 4.8]


In [2]:
import numpy as np

post_1 = np.array([120, 150, 180, 210, 200, 250, 310])
post_2 = np.array([85, 90, 110, 130, 125, 140, 160])
post_3 = np.array([300, 420, 390, 450, 480, 520, 600])
weekly_likes = np.vstack((post_1, post_2, post_3))
print("Stacked Array (Rows = Posts, Columns = Days):")
print(weekly_likes)

Stacked Array (Rows = Posts, Columns = Days):
[[120 150 180 210 200 250 310]
 [ 85  90 110 130 125 140 160]
 [300 420 390 450 480 520 600]]


In [3]:
import numpy as np

product_ids = np.array([
    "FLIP_101", "FLIP_102", "FLIP_103", "FLIP_104",
    "FLIP_105", "FLIP_106", "FLIP_107", "FLIP_108",
    "FLIP_109", "FLIP_110", "FLIP_111", "FLIP_112"
])
split_arrays = np.array_split(product_ids, 5)
for idx, part in enumerate(split_arrays, start=1):
    print(f"Part {idx} (Shape: {part.shape}): {part}")

Part 1 (Shape: (3,)): ['FLIP_101' 'FLIP_102' 'FLIP_103']
Part 2 (Shape: (3,)): ['FLIP_104' 'FLIP_105' 'FLIP_106']
Part 3 (Shape: (2,)): ['FLIP_107' 'FLIP_108']
Part 4 (Shape: (2,)): ['FLIP_109' 'FLIP_110']
Part 5 (Shape: (2,)): ['FLIP_111' 'FLIP_112']


In [4]:
import numpy as np

chat_activity = np.array([
    [15, 20, 12, 18, 25, 30, 22], 
    [5,   8,  4,  6,  7, 10,  5],  
    [35, 40, 28, 30, 45, 50, 48], 
    [12, 14, 11, 15, 13, 16, 18]   
])

new_user_activity = np.array([3, 2, 4, 1, 5, 2, 3]) 
chat_with_new = np.insert(chat_activity, 4, new_user_activity, axis=0)
print("Array after adding new user:")
print(chat_with_new)
total_messages_per_user = chat_with_new.sum(axis=1)
least_active_idx = np.argmin(total_messages_per_user)
print(f"\nTotal messages per user: {total_messages_per_user}")
print(f"User index to remove (lowest total): {least_active_idx}")
final_chat = np.delete(chat_with_new, least_active_idx, axis=0)
print("\nFinal array after removing the least active user:")
print(final_chat)

Array after adding new user:
[[15 20 12 18 25 30 22]
 [ 5  8  4  6  7 10  5]
 [35 40 28 30 45 50 48]
 [12 14 11 15 13 16 18]
 [ 3  2  4  1  5  2  3]]

Total messages per user: [142  45 276  99  20]
User index to remove (lowest total): 4

Final array after removing the least active user:
[[15 20 12 18 25 30 22]
 [ 5  8  4  6  7 10  5]
 [35 40 28 30 45 50 48]
 [12 14 11 15 13 16 18]]


In [5]:
import numpy as np  
youtube_views = np.array([1000, 1500, 2000, 2500, 3000])
youtube_views_view = youtube_views.view()
youtube_views_copy = youtube_views.copy()
youtube_views_view[0] = 9999    

youtube_views_copy[0] = 8888
print("Original array:")
print(youtube_views)
print("View array:")
print(youtube_views_view)
print("Copy array:")
print(youtube_views_copy)   

Original array:
[9999 1500 2000 2500 3000]
View array:
[9999 1500 2000 2500 3000]
Copy array:
[8888 1500 2000 2500 3000]
